# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: kafka-streams
image: pfisterb/kafka-streams:3.2.0
imagePullPolicy: Always

scapeInterval: 1s
replicas: 1

## Configurations to use a horizontal pod autoscaler
hpa:
  enabled: false
  maxScaleout: 3
  targetUtilization: 35
  stabilizationWindow: 300

