# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: flink-reactive
image: pfisterb/flink:1.16.0
imagePullPolicy: Always
# nodePort: 30881
scapeInterval: 1s
# de.tu_berlin.dos.arm.wordcount.processor.WordCount, de.tu_berlin.dos.arm.traffic_monitoring.processor.Run
jobClassname: "de.tu_berlin.dos.arm.yahoo_streaming_benchmark.processor.Run"

## Configurations to use a horizontal pod autoscaler
hpa:
  enabled: false
  maxScaleout: 3
  targetUtilization: 35
  stabilizationWindow: 300

## Change flink jobmanager configuration parameters below:
jobmanager:
  replicas: 1

  ## jobmanager.memory.process.size in configmap
  configMemory: "1600m"

  ## Liveness (and eventually Readiness) probe values.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 60

  resources:
    requests:
      #memory: "64Mi"
      cpu: "1000m"
    limits:
      #memory: "128Mi"
      cpu: "1000m"

## Change flink taskmanager configuration parameters below:
taskmanager:
  replicas: 1

  resources:
    requests:
      #memory: "64Mi"
      cpu: "1000m"
    limits:
      #memory: "128Mi"
      cpu: "1000m"

  ## taskmanager.memory.process.size in configmap
  configMemory: "3096m"

  ## Liveness (and eventually Readiness) probe values.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 60

## High availability configurations
highAvailability:
  enabled: false

  ## The path where metadata for master recovery is persisted. While ZooKeeper stores
  ## the small ground truth for checkpoint and leader election, this location stores
  ## the larger objects, like persisted dataflow graphs.
  ##
  ## Must be a durable file system that is accessible from all nodes
  ## (like HDFS, S3, Ceph, nfs, ...)
  storageDir: hdfs:///flink/ha

  ## The ID of the Flink cluster, used to separate multiple Flink clusters from each other.
  ## Needs to be set for standalone clusters but is automatically inferred in YARN and Mesos.
  clusterId: /flink
